### PR TITLE
Document CC database encryption validation and how to skip it

### PR DESCRIPTION
**Pull request by ewrenn8**
Please don't merge until @zrob has given the 👌 - Thanks!

[#160565567]

Signed-off-by: Eli Wrenn <ewrenn@pivotal.io>

### CODE REVIEW

**Comment by zrob** [comment]
looks good!

**Comment by pspinrad** [comment]
Thanks @ewrenn8 -- quick question: what runs the validations before and during deployment? Is it the CC itself, or a some errand, or?? Thanks!

**Comment by selzoc** [comment]
@pspinrad The validations are split between the bosh templating (for those not requiring knowledge of the contents of the database) to a rake task that runs during cc pre-start.

**Comment by pspinrad** [comment]
@selzoc @ewrenn8 thanks!

**Pull request merged**
