### PR TITLE
Document that manifest quotas updates don't apply

### PR DESCRIPTION
**Pull request by mtekel**
Add a note that updates to quotas in manifest are not applied.

This addresses https://github.com/cloudfoundry/capi-release/issues/31

### CODE REVIEW

**Comment by SocalNick** [comment]
Hi Docs, let me know if you accept this PR and I will close https://github.com/cloudfoundry/capi-release/issues/31

**Comment by bentarnoff** [comment]
Thanks, @mtekel !

**Comment by bentarnoff** [comment]
@SocalNick accepted!

**Comment by mtekel** [comment]
Out of curiosity, how often do you deploy documentation web page? I couldn't see the changes yet on https://docs.cloudfoundry.org/adminguide/quota-plans.html#manifest

**Comment by bentarnoff** [comment]
Hey @mtekel you can see the change on our staging site here: http://docs-cloudfoundry-staging.cfapps.io/adminguide/quota-plans.html. Also, I've just bumped our build, so you should see the updated topic on the production site soon.

**Pull request merged**
