### PR TITLE
Document that cc encryption label/value mapping should be maintained

### PR DESCRIPTION
**Pull request by ewrenn8**
Please do not merge until @zrob gives the go-ahead, thanks!

[#160563628]

Signed-off-by: Eli Wrenn <ewrenn@pivotal.io>

### CODE REVIEW

**Comment by zrob** [comment]
hey @ewrenn8 how does this interact with https://github.com/cloudfoundry/docs-cf-admin/pull/129

**Comment by ewrenn8** [comment]
@zrob They should be separate from each other

**Comment by zrob** [comment]
looks good to me!

**Comment by pspinrad** [comment]
Thanks @ewrenn8 and @zrob !

**Pull request merged**
