### PR TITLE
Add cc configration documentation to routing isolation segments page

### PR DESCRIPTION
**Pull request by belinda-liu**
-cc.diego.temporary_local_apps flag must be set to true

[#146390475]

Let us know if you have any questions.
Thanks,
CF Routing
@jberkhahn and @belinda-liu

### CODE REVIEW

**Comment by ljarzynski** [comment]
HI @belinda-liu ! Landon from PCF Docs here. Let us know once you follow cfdreddbot's instructions to sign or make your membership public for the CLA. Then I can close/reopen the PR to verify and we can merge/review :). Thanks!

**Comment by belinda-liu** [comment]
@ljarzynski just publicized my membership! Let me know if there's anything else.

**Comment by ljarzynski** [comment]
@belinda-liu Looks like we're all good! Thanks! I'll review and reach out with any questions. Should be merged shortly!

**Comment by ljarzynski** [comment]
Thanks @belinda-liu ! @jberkhahn !

**Pull request merged**
