### PR TITLE
Add documentation for configuring load balancers

### PR DESCRIPTION
**Pull request by shashwathi**
Hi, 

This PR adds documentation for operators to configure Load balancers to CF deployment. This covers the below 3 cases

1. Configure LB infront of Haproxy
1. Configure LB infront of gorouter
1. Configure LB infront of TCP router

Regards
Shash && Swetha
CF routing team

### CODE REVIEW

**Comment by ljarzynski** [comment]
Hi @shashwathi! Thanks for the PR! Would you mind taking a look at this Google doc I made and answering the comments? There are a few things I think we can clarify before merging.

https://docs.google.com/a/pivotal.io/document/d/1_SOuRM3QapI3iG9ZqhfuhBr2yxD6zTOFhF2tr7fbALI/edit?usp=sharing

**Comment by shashwathi** [comment]
@ljarzynski : I have answered your questions on the doc to the best of my knowledge. Do you have any further clarifications on the PR? 

Regards
Shash

**Comment by ljarzynski** [comment]
@shashwathi Thank you for answering the questions. I did have one additional thing I wanted to clarify which was: 

1. What is the property name for the healthcheck endpoint for ha proxy that you configure in the cf-release manifest (the last section of the doc)?

**Comment by ljarzynski** [comment]
@shashwathi Thanks for answering the questions! I think I understand better now. I tried to add some headings to organize the page and also added some clarification and an intro sentence. Let me know if you have any feedback!

http://docs-cloudfoundry-staging.cfapps.io/adminguide/configure-lb-healthceck.html

**Comment by shashwathi** [comment]
@ljarzynski : It looks great! I think the description is much more clear and it is organized better. Thank you for your efforts.

Regards
Shash

**Pull request closed without merging**
