### PR TITLE
update troubleshooting slow requests

### PR DESCRIPTION
**Pull request by ameowlia**
* add more experiments to narrow down where latency is originating

[#170161002](https://www.pivotaltracker.com/story/show/170161002)

### CODE REVIEW

**Comment by ameowlia** [comment]
1. I keep having CLA trouble even though I have signed it and I am a pivotal employee.  :( 
2. I only made this PR for one branch, but is applicable for all supported versions of PAS and their corresponding CF versions.

I am happy to work on this with anyone on the docs team, I know I made a lot of changes here. Please reach out on slack in the #pcf-networking channel. My handle is: @ameowlia .

**Comment by mjgutermuth** [comment]
Hi @ameowlia! Thank you so much for this awesome PR!! I'm not sure why the bot is complaining, but as a Pivotal employee you are covered under the corporate CLA so merging this is not a problem.

**Comment by ameowlia** [comment]
Thanks @mjgutermuth!!!

Should I open a PR to the other versions (2.5+) or is there a better way to get it on all versions?

**Comment by mjgutermuth** [comment]
No problem @ameowlia! I can cherry-pick everything to the other doc versions. Thanks again!!

**Pull request merged**
