### PR TITLE
add description to app security group rules

### PR DESCRIPTION
**Pull request by youreddy**
https://www.pivotaltracker.com/story/show/99729506

### CODE REVIEW

**Comment by youreddy** [comment]
please don't merge until @SocalNick give the thumbs up

**Comment by SocalNick** [comment]
👍  This can be published with CF-238

**Comment by bentarnoff** [comment]
Thanks, @youreddy and @SocalNick! We'll block on release of CF-238, and then push.

**Comment by bentarnoff** [comment]
Hey @youreddy and @SocalNick, we can make these changes now that CF 238 has been cut, but the Application Security Groups topic that you made this PR against has changed substantially. I've added your changes into the newly revised topic, but please take a look to see if it satisfies your request.

Github commit: https://github.com/cloudfoundry/docs-cf-admin/commit/d9e9d10b88676ca0f0c4e32ca49ca1fa7aab52ff
Staging site: http://docs-cloudfoundry-staging.cfapps.io/adminguide/app-sec-groups.html

I'm closing this because the changes should be reflected above, but please get in touch if you have any additional feedback. Thanks.

**Comment by SocalNick** [comment]
Looks great @bentarnoff, feel free to merge!

**Comment by bentarnoff** [comment]
Thanks, @SocalNick ! Will do.

**Pull request closed without merging**
